import SeoHuiChan from '@/images/seminar/presenter/seohuichan.png';
import { SeminarThumnail } from '@/interfaces/seminar/seminarThumbnail';

export const SEMINAR_DATA: SeminarThumnail[] = [
    {
        id: 1,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: `
        휴, 하마터면 
        의사 될 뻔...
        `,
        description: `
        의사를 목표로 공부를 하다가,
        프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들
        `,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 2,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 3,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 4,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 5,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 6,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 7,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 8,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 9,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 10,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 11,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 12,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 13,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
    {
        id: 14,
        flag: 1,
        type: 'Camping Seminar',
        topic: 'DevTalk',
        date: '2023.09.22 (FRI) 19:30',
        location: '동국대학교 원흥관 PBL',
        title: '휴, 하마터면\n의사 될 뻔...',
        description: `의사를 목표로 공부를 하다가, 프로그래밍을 시작한 과정들을 토대로 개발 공부를 하며 깨달은 것들`,
        presenter: '서희찬',
        role: 'Lead',
        profile_image_url: SeoHuiChan.src,
    },
]