export const AIML_MEMBERS = [
  {
    id: 1,
    name: '이선호',
    role: 'Core',
    department: 'AI/ML',
    description: 'Focused on core system architecture and backend development.',
    image: '/images/members/lead.png',
  },
  {
    id: 2,
    name: '김윤지',
    role: 'Core',
    department: 'AI/ML',
    description:
      'Leads the core development team with a focus on innovation and performance.',
    image: '/images/members/lead.png',
  },
  {
    id: 3,
    name: '김현진',
    role: 'General',
    department: '산업시스템공학과',
    description:
      'Works on user interface design and user experience optimization.',
    image: '/images/members/lead.png',
  },
  {
    id: 4,
    name: '남경현',
    role: 'General',
    department: '산업시스템공학과',
    description:
      'Implements digital marketing strategies to enhance product visibility.',
    image: '/images/members/lead.png',
  },
  {
    id: 5,
    name: '양나은',
    role: 'General',
    department: '융합소프트웨어, 화공생물공학과',
    description: 'Provides customer support and technical assistance.',
    image: '/images/members/lead.png',
  },
  {
    id: 6,
    name: '이다원',
    role: 'General',
    department: '컴퓨터공학전공',
    description: 'Ensures software quality through rigorous testing.',
    image: '/images/members/lead.png',
  },
  {
    id: 7,
    name: '이윤주',
    role: 'General',
    department: '인공지능학과',
    description:
      'Conducts research to keep the team updated with the latest tech trends.',
    image: '/images/members/lead.png',
  },
  {
    id: 8,
    name: '한상훈',
    role: 'General',
    department: '멀티미디어공학과',
    description:
      'Manages recruitment and ensures a healthy workplace environment.',
    image: '/images/members/lead.png',
  },
  {
    id: 9,
    name: '한종원',
    role: 'General',
    department: '산업시스템공학과',
    description: 'Oversees financial operations and budget planning.',
    image: '/images/members/lead.png',
  },
  {
    id: 10,
    name: '홍민기',
    role: 'General',
    department: '컴퓨터공학전공',
    description: 'Coordinates day-to-day operational activities.',
    image: '/images/members/lead.png',
  },
  {
    id: 11,
    name: '이재윤',
    role: 'General',
    department: '멀티미디어공학과',
    description: 'Coordinates day-to-day operational activities.',
    image: '/images/members/lead.png',
  },
];
