export const SERVER_MEMBERS = [
  {
    id: 1,
    name: '박상준',
    role: 'Core',
    department: 'Server/Cloud',
    description: 'Focused on core system architecture and backend development.',
    image: '/images/members/lead.png',
  },
  {
    id: 2,
    name: '손형준',
    role: 'Core',
    department: 'Server/Cloud',
    description:
      'Leads the core development team with a focus on innovation and performance.',
    image: '/images/members/lead.png',
  },
  {
    id: 3,
    name: '강산아',
    role: 'General',
    department: '스포츠문화학과',
    description:
      'Works on user interface design and user experience optimization.',
    image: '/images/members/lead.png',
  },
  {
    id: 4,
    name: '강승준',
    role: 'General',
    department: '멀티미디어공학과',
    description:
      'Implements digital marketing strategies to enhance product visibility.',
    image: '/images/members/lead.png',
  },
  {
    id: 5,
    name: '고나연',
    role: 'General',
    department: '컴퓨터공학전공',
    description: 'Provides customer support and technical assistance.',
    image: '/images/members/lead.png',
  },
  {
    id: 6,
    name: '김재니',
    role: 'General',
    department: '정보통신공학과',
    description: 'Ensures software quality through rigorous testing.',
    image: '/images/members/lead.png',
  },
  {
    id: 7,
    name: '윤창섭',
    role: 'General',
    department: '정보통신공학과',
    description:
      'Conducts research to keep the team updated with the latest tech trends.',
    image: '/images/members/lead.png',
  },
  {
    id: 8,
    name: '장동겸',
    role: 'General',
    department: '컴퓨터공학전공',
    description:
      'Manages recruitment and ensures a healthy workplace environment.',
    image: '/images/members/lead.png',
  },
  {
    id: 9,
    name: '임은서',
    role: 'General',
    department: '정보통신공학과',
    description: 'Oversees financial operations and budget planning.',
    image: '/images/members/lead.png',
  },
  {
    id: 10,
    name: '정구연',
    role: 'General',
    department: '컴퓨터공학전공',
    description: 'Coordinates day-to-day operational activities.',
    image: '/images/members/lead.png',
  },
  {
    id: 11,
    name: '임정우',
    role: 'General',
    department: '정보통신공학과',
    description: 'Coordinates day-to-day operational activities.',
    image: '/images/members/lead.png',
  },
];
